[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -Dserver.port=${PORT:-8080} -jar target/barbershop-backend-0.0.1-SNAPSHOT.jar"
